/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JFileChooser;
import java.io.File;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.PersonalProfile;
import util.Validations;

/**
 *
 * @author shivanginagar
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    PersonalProfile person;

    public CreateJPanel(PersonalProfile person) {
        initComponents();
        this.person = person;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtemail4 = new javax.swing.JTextField();
        Labelname1 = new javax.swing.JLabel();
        txtemail7 = new javax.swing.JTextField();
        Labelemailaddress4 = new javax.swing.JLabel();
        Labelgeodata1 = new javax.swing.JLabel();
        txtemail5 = new javax.swing.JTextField();
        Labeltelnum1 = new javax.swing.JLabel();
        Labelfaxnum1 = new javax.swing.JLabel();
        txtfaxnum1 = new javax.swing.JTextField();
        txtName1 = new javax.swing.JTextField();
        txtdob1 = new javax.swing.JTextField();
        Labelemailaddress6 = new javax.swing.JLabel();
        Labeltitle1 = new javax.swing.JLabel();
        txtgeographicdata1 = new javax.swing.JTextField();
        Labelemailaddress5 = new javax.swing.JLabel();
        Labeldob1 = new javax.swing.JLabel();
        Labelemailaddress7 = new javax.swing.JLabel();
        txtemail6 = new javax.swing.JTextField();
        txttelnum1 = new javax.swing.JTextField();
        txttelnum = new javax.swing.JTextField();
        txtgeographicdata = new javax.swing.JTextField();
        LabelCreateProfile = new javax.swing.JLabel();
        txtdob = new javax.swing.JTextField();
        Labelname = new javax.swing.JLabel();
        txtfaxnum = new javax.swing.JTextField();
        Labelgeodata = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        Labeltelnum = new javax.swing.JLabel();
        btnsave = new javax.swing.JButton();
        LabelSSN = new javax.swing.JLabel();
        Labeldob = new javax.swing.JLabel();
        Labelfaxnum = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        Labelemail = new javax.swing.JLabel();
        LabelMRN = new javax.swing.JLabel();
        LabelHBP = new javax.swing.JLabel();
        txtMRN = new javax.swing.JTextField();
        txtHBP = new javax.swing.JTextField();
        txtSSN = new javax.swing.JTextField();
        txtlinkedin = new javax.swing.JTextField();
        txtvehicleid = new javax.swing.JTextField();
        txtdeviceid = new javax.swing.JTextField();
        txtIPadd = new javax.swing.JTextField();
        LabelBankaccnum = new javax.swing.JLabel();
        txtuniquecode = new javax.swing.JTextField();
        Labellicensenum = new javax.swing.JLabel();
        Labeluniquecode = new javax.swing.JLabel();
        Labelvehicleid = new javax.swing.JLabel();
        Labellinkedin = new javax.swing.JLabel();
        txtBankaccnum = new javax.swing.JTextField();
        LabelIPadd = new javax.swing.JLabel();
        txtlicensenum = new javax.swing.JTextField();
        Labeldeviceid1 = new javax.swing.JLabel();
        LabelPhoto = new javax.swing.JLabel();
        btnbrowse = new javax.swing.JButton();
        lblFileName = new javax.swing.JLabel();

        Labelname1.setText("Name :");

        Labelemailaddress4.setText("Medical Record Number :");

        Labelgeodata1.setText("Geographic Data :");

        Labeltelnum1.setText("Telephone Number :");

        Labelfaxnum1.setText("Fax Number :");

        txtName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtName1ActionPerformed(evt);
            }
        });

        Labelemailaddress6.setText("SSN :");

        Labeltitle1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        Labeltitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Labeltitle1.setText("Create Profile");

        Labelemailaddress5.setText("HBP Number :");

        Labeldob1.setText("Date of Birth :");

        Labelemailaddress7.setText("Email Address :");

        LabelCreateProfile.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        LabelCreateProfile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelCreateProfile.setText("Create Profile");

        Labelname.setText("Name :");

        Labelgeodata.setText("Geographic Data :");

        Labeltelnum.setText("Telephone Number :");

        btnsave.setText("S A V E");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        LabelSSN.setText("SSN :");

        Labeldob.setText("DOB  (dd/mm/yyyy) :");

        Labelfaxnum.setText("Fax Number :");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        Labelemail.setText("Email Address :");

        LabelMRN.setText("Medical Record Number :");

        LabelHBP.setText("HBP Number :");

        LabelBankaccnum.setText("Bank Acc Number : ");

        Labellicensenum.setText("License number");

        Labeluniquecode.setText("Unique Code :");

        Labelvehicleid.setText("Vehicle Identifier :");

        Labellinkedin.setText("LinkedIn :");

        txtBankaccnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBankaccnumActionPerformed(evt);
            }
        });

        LabelIPadd.setText("IP Address :");

        Labeldeviceid1.setText("Device Identifier :");

        LabelPhoto.setText("Profile Photo :");

        btnbrowse.setText("Browse");
        btnbrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbrowseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LabelMRN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LabelSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelHBP, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHBP, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMRN, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(Labelname, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(Labelfaxnum, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(Labelemail, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(Labeltelnum, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(Labelgeodata, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(Labeldob, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtemail)
                            .addComponent(txtfaxnum, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttelnum, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdob, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtgeographicdata, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(278, 278, 278)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(LabelBankaccnum, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(Labelvehicleid, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtvehicleid, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtBankaccnum, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Labellicensenum, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Labeldeviceid1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtdeviceid, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                .addComponent(txtlicensenum))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(LabelPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(56, 56, 56)
                            .addComponent(btnbrowse))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Labellinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtlinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Labeluniquecode)
                                .addGap(41, 41, 41)
                                .addComponent(txtuniquecode, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(LabelIPadd, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtIPadd, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(35, 35, 35)
                .addComponent(lblFileName, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(311, 311, 311))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelCreateProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(292, 292, 292))
            .addGroup(layout.createSequentialGroup()
                .addGap(502, 502, 502)
                .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LabelCreateProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Labelname, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Labelgeodata, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtgeographicdata, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtdob, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Labeldob, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txttelnum, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Labeltelnum, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBankaccnum, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelBankaccnum, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Labelvehicleid, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtvehicleid, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtdeviceid, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Labeldeviceid1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtlicensenum, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Labellicensenum, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtfaxnum, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Labelfaxnum, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtlinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Labellinkedin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Labelemail, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtIPadd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LabelIPadd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMRN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelMRN, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHBP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelHBP, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtuniquecode, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Labeluniquecode, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelPhoto)
                            .addComponent(btnbrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFileName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:

        storeProfileData();

        JOptionPane.showMessageDialog(this, "Personal Information Saved");

    }//GEN-LAST:event_btnsaveActionPerformed

    private void txtName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtName1ActionPerformed

    private void txtBankaccnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBankaccnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBankaccnumActionPerformed

    private void btnbrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbrowseActionPerformed
        // TODO add your handling code here:
        
        JFileChooser jFileChooser = new JFileChooser();
        jFileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images", "jpg","gif","png");
        jFileChooser.addChoosableFileFilter(filter);
          int result = jFileChooser.showSaveDialog(null);
           //if the user click on save in Jfilechooser
          if(result == JFileChooser.APPROVE_OPTION){
              File selectedFile = jFileChooser.getSelectedFile();
              String path = selectedFile.getAbsolutePath();
              lblFileName.setText(selectedFile.getName());
              person.setPhoto(path);
              //label.setIcon(ResizeImage(path));
          }
          else if(result == JFileChooser.CANCEL_OPTION){
              lblFileName.setText("No file selected");
          }
        
    }//GEN-LAST:event_btnbrowseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelBankaccnum;
    private javax.swing.JLabel LabelCreateProfile;
    private javax.swing.JLabel LabelHBP;
    private javax.swing.JLabel LabelIPadd;
    private javax.swing.JLabel LabelMRN;
    private javax.swing.JLabel LabelPhoto;
    private javax.swing.JLabel LabelSSN;
    private javax.swing.JLabel Labeldeviceid1;
    private javax.swing.JLabel Labeldob;
    private javax.swing.JLabel Labeldob1;
    private javax.swing.JLabel Labelemail;
    private javax.swing.JLabel Labelemailaddress4;
    private javax.swing.JLabel Labelemailaddress5;
    private javax.swing.JLabel Labelemailaddress6;
    private javax.swing.JLabel Labelemailaddress7;
    private javax.swing.JLabel Labelfaxnum;
    private javax.swing.JLabel Labelfaxnum1;
    private javax.swing.JLabel Labelgeodata;
    private javax.swing.JLabel Labelgeodata1;
    private javax.swing.JLabel Labellicensenum;
    private javax.swing.JLabel Labellinkedin;
    private javax.swing.JLabel Labelname;
    private javax.swing.JLabel Labelname1;
    private javax.swing.JLabel Labeltelnum;
    private javax.swing.JLabel Labeltelnum1;
    private javax.swing.JLabel Labeltitle1;
    private javax.swing.JLabel Labeluniquecode;
    private javax.swing.JLabel Labelvehicleid;
    private javax.swing.JButton btnbrowse;
    private javax.swing.JButton btnsave;
    private javax.swing.JLabel lblFileName;
    private javax.swing.JTextField txtBankaccnum;
    private javax.swing.JTextField txtHBP;
    private javax.swing.JTextField txtIPadd;
    private javax.swing.JTextField txtMRN;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtName1;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtdeviceid;
    private javax.swing.JTextField txtdob;
    private javax.swing.JTextField txtdob1;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtemail4;
    private javax.swing.JTextField txtemail5;
    private javax.swing.JTextField txtemail6;
    private javax.swing.JTextField txtemail7;
    private javax.swing.JTextField txtfaxnum;
    private javax.swing.JTextField txtfaxnum1;
    private javax.swing.JTextField txtgeographicdata;
    private javax.swing.JTextField txtgeographicdata1;
    private javax.swing.JTextField txtlicensenum;
    private javax.swing.JTextField txtlinkedin;
    private javax.swing.JTextField txttelnum;
    private javax.swing.JTextField txttelnum1;
    private javax.swing.JTextField txtuniquecode;
    private javax.swing.JTextField txtvehicleid;
    // End of variables declaration//GEN-END:variables

    private void storeProfileData() {
        if (Validations.checkValidationsForName(txtName.getText().trim())) {
            person.setName(txtName.getText().trim());
        } else {
            JOptionPane.showMessageDialog(this, "Invalid Name");
            return;
        }
        

        if (Validations.checkValidationsForGeoData(txtgeographicdata.getText().trim())) {
            person.setGeographicdata(txtgeographicdata.getText().trim());
        } else {
            JOptionPane.showMessageDialog(this, "Invalid Geographic Data");
            return;
        }
        
        if (Validations.checkValidationsForDOB(txtdob.getText().trim())) {
          person.setDateofbirth(txtdob.getText().trim());
        } else {
          JOptionPane.showMessageDialog(this, "Invalid DOB Data");
           return;
        }
       
        if (Validations.checkValidationsForTelNum(txttelnum.getText().trim())) {
            person.setTelnum(Long.parseLong(txttelnum.getText()));
        } else {
            JOptionPane.showMessageDialog(this, "Invalid Telephone Number");
            return;
        }
        
        if (Validations.checkValidationsForFaxNum(txtfaxnum.getText().trim())) {
            person.setFaxnum(Long.parseLong(txtfaxnum.getText()));
        } else {
            JOptionPane.showMessageDialog(this, "Invalid Fax Number");
            return;
        }
        
        if (Validations.checkValidationsForEmail(txtemail.getText().trim())) {
            person.setEmail(txtemail.getText());
        } else {
            JOptionPane.showMessageDialog(this, "Invalid EmailAddress");
            return;
        }
        
        if (Validations.checkValidationsForSSN(txtSSN.getText().trim())) {
            person.setSSN(Long.parseLong(txtSSN.getText()));
        } else {
            JOptionPane.showMessageDialog(this, "Invalid SSN");
            return;
        }
        
        if (Validations.checkValidationsForMRN(txtMRN.getText().trim())) {
            person.setMedicalrecordnum(Long.parseLong(txtMRN.getText()));
        } else {
            JOptionPane.showMessageDialog(this, "Invalid Medical Record Number");
            return;
        }
        
        if (Validations.checkValidationsForHBPN(txtHBP.getText().trim())) {
            person.setHPBnum(Long.parseLong(txtHBP.getText()));
        } else {
            JOptionPane.showMessageDialog(this, "Invalid HBP Number");
            return;
        }
        
        if (Validations.checkValidationsForBankaccnum(txtBankaccnum.getText().trim())) {
            person.setBankaccountnum(Long.parseLong(txtBankaccnum.getText()));
        } else {
            JOptionPane.showMessageDialog(this, "Invalid Bank Account Number");
            return;
        }
        
        if (Validations.checkValidationsForVehicleID(txtvehicleid.getText().trim())) {
            person.setVehicleidentifier(txtvehicleid.getText().trim());
        } else {
            JOptionPane.showMessageDialog(this, "Invalid Vehicle ID");
            return;
        }
        
        if (Validations.checkValidationsForDeviceID(txtdeviceid.getText().trim())) {
            person.setDeviceidentifier(txtdeviceid.getText().trim());
        } else {
            JOptionPane.showMessageDialog(this, "Invalid Device ID");
            return;
        }
        
        
        if (Validations.checkValidationsForLicensenumber(txtlicensenum.getText().trim())) {
            person.setLicensenum(txtlicensenum.getText().trim());
        } else {
            JOptionPane.showMessageDialog(this, "Invalid License Number");
            return;
        }
        
        if (Validations.checkValidationsForLinkedin(txtlinkedin.getText().trim())) {
            person.setLinkedin(txtlinkedin.getText().trim());
        } else {
            JOptionPane.showMessageDialog(this, "Invalid LinkedIn Profile");
            return;
        }
        
        if (Validations.checkValidationsForIPAddress(txtIPadd.getText().trim())) {
            person.setIPaddress(txtIPadd.getText().trim());
        } else {
            JOptionPane.showMessageDialog(this, "Invalid IP Address");
            return;
        }
        
        if (Validations.checkValidationsForUniqueCode(txtuniquecode.getText().trim())) {
            person.setUniqidcode(txtuniquecode.getText().trim());
        } else {
            JOptionPane.showMessageDialog(this, "Invalid Unique Code");
            return;
        }
        

       
    }
    
    
    
}
    
    
    
    


