/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Image;
import model.PersonalProfile;
import javax.swing.ImageIcon;

/**
 *
 * @author shivanginagar
 */
public class DisplayJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DisplayJPanel
     */
    private PersonalProfile person;

    public DisplayJPanel(PersonalProfile person) {
        initComponents();

        this.person = person;
        displaypersonalinfo();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Labelemailaddress2 = new javax.swing.JLabel();
        Labelemailaddress3 = new javax.swing.JLabel();
        txtemail1 = new javax.swing.JTextField();
        txtemail2 = new javax.swing.JTextField();
        txtemail3 = new javax.swing.JTextField();
        txttelnum1 = new javax.swing.JTextField();
        txttelnum2 = new javax.swing.JTextField();
        txtgeographicdata2 = new javax.swing.JTextField();
        txtdob2 = new javax.swing.JTextField();
        txtgeographicdata1 = new javax.swing.JTextField();
        txtfaxnum2 = new javax.swing.JTextField();
        Labeltitle1 = new javax.swing.JLabel();
        Labelgeodata2 = new javax.swing.JLabel();
        txtdob1 = new javax.swing.JTextField();
        txtemail11 = new javax.swing.JTextField();
        Labelname1 = new javax.swing.JLabel();
        Labeltelnum2 = new javax.swing.JLabel();
        txtfaxnum1 = new javax.swing.JTextField();
        Labelgeodata1 = new javax.swing.JLabel();
        txtemail4 = new javax.swing.JTextField();
        Labeltelnum1 = new javax.swing.JLabel();
        btnsave = new javax.swing.JButton();
        Labelemailaddress1 = new javax.swing.JLabel();
        Labelemailaddress10 = new javax.swing.JLabel();
        Labeldob2 = new javax.swing.JLabel();
        Labelfaxnum2 = new javax.swing.JLabel();
        txtName2 = new javax.swing.JTextField();
        Labelemailaddress11 = new javax.swing.JLabel();
        Labeldob1 = new javax.swing.JLabel();
        Labelfaxnum1 = new javax.swing.JLabel();
        txtName1 = new javax.swing.JTextField();
        Labelemailaddress4 = new javax.swing.JLabel();
        LabelMRN = new javax.swing.JLabel();
        LabelHBP = new javax.swing.JLabel();
        txtMRN = new javax.swing.JTextField();
        txtHBP = new javax.swing.JTextField();
        txtSSN = new javax.swing.JTextField();
        txttelnum = new javax.swing.JTextField();
        txtlinkedin = new javax.swing.JTextField();
        txtvehicleid = new javax.swing.JTextField();
        txtdeviceid = new javax.swing.JTextField();
        txtgeographicdata = new javax.swing.JTextField();
        txtIPadd = new javax.swing.JTextField();
        LabelDisplayprofile = new javax.swing.JLabel();
        LabelBankaccnum = new javax.swing.JLabel();
        txtdob = new javax.swing.JTextField();
        txtuniquecode = new javax.swing.JTextField();
        Labelname = new javax.swing.JLabel();
        Labeldeviceid = new javax.swing.JLabel();
        txtfaxnum = new javax.swing.JTextField();
        Labelgeodata = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        Labeltelnum = new javax.swing.JLabel();
        LabelSSN = new javax.swing.JLabel();
        Labeluniquecode = new javax.swing.JLabel();
        Labelvehicleid = new javax.swing.JLabel();
        Labellinkedin = new javax.swing.JLabel();
        txtBankaccnum = new javax.swing.JTextField();
        LabelIPadd = new javax.swing.JLabel();
        Labeldob = new javax.swing.JLabel();
        Labelfaxnum = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        Labelemail = new javax.swing.JLabel();
        txtlicense = new javax.swing.JTextField();
        Labellicense = new javax.swing.JLabel();
        LabelPhoto = new javax.swing.JLabel();
        txtPhoto = new javax.swing.JLabel();

        Labelemailaddress2.setText("Medical Record Number :");

        Labelemailaddress3.setText("HBP Number :");

        Labeltitle1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        Labeltitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Labeltitle1.setText("Create Profile");

        Labelgeodata2.setText("Bank Acc Number : ");

        Labelname1.setText("Name :");

        Labeltelnum2.setText("Device Identifier :");

        Labelgeodata1.setText("Geographic Data :");

        Labeltelnum1.setText("Telephone Number :");

        btnsave.setText("S A V E");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        Labelemailaddress1.setText("SSN :");

        Labelemailaddress10.setText("Unique Code :");

        Labeldob2.setText("Vehicle Identifier :");

        Labelfaxnum2.setText("LinkedIn :");

        txtName2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtName2ActionPerformed(evt);
            }
        });

        Labelemailaddress11.setText("IP Address :");

        Labeldob1.setText("Date of Birth :");

        Labelfaxnum1.setText("Fax Number :");

        txtName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtName1ActionPerformed(evt);
            }
        });

        Labelemailaddress4.setText("Email Address :");

        LabelMRN.setText("Medical Record Number :");

        LabelHBP.setText("HBP Number :");

        LabelDisplayprofile.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        LabelDisplayprofile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelDisplayprofile.setText("Display Profile");

        LabelBankaccnum.setText("Bank Acc Number : ");

        Labelname.setText("Name :");

        Labeldeviceid.setText("Device Identifier :");

        Labelgeodata.setText("Geographic Data :");

        Labeltelnum.setText("Telephone Number :");

        LabelSSN.setText("SSN :");

        Labeluniquecode.setText("Unique Code :");

        Labelvehicleid.setText("Vehicle Identifier :");

        Labellinkedin.setText("LinkedIn :");

        txtBankaccnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBankaccnumActionPerformed(evt);
            }
        });

        LabelIPadd.setText("IP Address :");

        Labeldob.setText("Date of Birth :");

        Labelfaxnum.setText("Fax Number :");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        Labelemail.setText("Email Address :");

        txtlicense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlicenseActionPerformed(evt);
            }
        });

        Labellicense.setText("License Number :");

        LabelPhoto.setText("Profile Photo :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LabelMRN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LabelSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelHBP, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHBP, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMRN, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(Labelname, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(Labelgeodata, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(Labeldob, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(Labeltelnum, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(Labelfaxnum, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(Labelemail, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtemail)
                            .addComponent(txtfaxnum, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttelnum, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdob, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtgeographicdata, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(278, 278, 278)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelBankaccnum, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(Labelvehicleid, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtvehicleid, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBankaccnum, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 2, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Labeldeviceid, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(Labellicense, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtlicense)
                            .addComponent(txtdeviceid, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Labellinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtlinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(LabelIPadd, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtIPadd, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(Labeluniquecode)
                                        .addGap(41, 41, 41))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LabelPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(24, 24, 24)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtuniquecode, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))))))
                .addGap(463, 463, 463))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelDisplayprofile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(292, 292, 292))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBankaccnum, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelBankaccnum, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Labelvehicleid, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtvehicleid, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Labeldeviceid, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdeviceid, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Labellinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Labellicense, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtlicense, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtlinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIPadd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelIPadd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LabelDisplayprofile, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Labelname, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Labelgeodata, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtgeographicdata, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtdob, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Labeldob, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txttelnum, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Labeltelnum, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfaxnum, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Labelfaxnum, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Labelemail, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtuniquecode, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Labeluniquecode, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMRN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelMRN, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelPhoto)
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHBP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelHBP, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                .addContainerGap(59, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:

      
    }//GEN-LAST:event_btnsaveActionPerformed

    private void txtName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtName2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtName2ActionPerformed

    private void txtName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtName1ActionPerformed

    private void txtBankaccnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBankaccnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBankaccnumActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtlicenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlicenseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlicenseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelBankaccnum;
    private javax.swing.JLabel LabelDisplayprofile;
    private javax.swing.JLabel LabelHBP;
    private javax.swing.JLabel LabelIPadd;
    private javax.swing.JLabel LabelMRN;
    private javax.swing.JLabel LabelPhoto;
    private javax.swing.JLabel LabelSSN;
    private javax.swing.JLabel Labeldeviceid;
    private javax.swing.JLabel Labeldob;
    private javax.swing.JLabel Labeldob1;
    private javax.swing.JLabel Labeldob2;
    private javax.swing.JLabel Labelemail;
    private javax.swing.JLabel Labelemailaddress1;
    private javax.swing.JLabel Labelemailaddress10;
    private javax.swing.JLabel Labelemailaddress11;
    private javax.swing.JLabel Labelemailaddress2;
    private javax.swing.JLabel Labelemailaddress3;
    private javax.swing.JLabel Labelemailaddress4;
    private javax.swing.JLabel Labelfaxnum;
    private javax.swing.JLabel Labelfaxnum1;
    private javax.swing.JLabel Labelfaxnum2;
    private javax.swing.JLabel Labelgeodata;
    private javax.swing.JLabel Labelgeodata1;
    private javax.swing.JLabel Labelgeodata2;
    private javax.swing.JLabel Labellicense;
    private javax.swing.JLabel Labellinkedin;
    private javax.swing.JLabel Labelname;
    private javax.swing.JLabel Labelname1;
    private javax.swing.JLabel Labeltelnum;
    private javax.swing.JLabel Labeltelnum1;
    private javax.swing.JLabel Labeltelnum2;
    private javax.swing.JLabel Labeltitle1;
    private javax.swing.JLabel Labeluniquecode;
    private javax.swing.JLabel Labelvehicleid;
    private javax.swing.JButton btnsave;
    private javax.swing.JTextField txtBankaccnum;
    private javax.swing.JTextField txtHBP;
    private javax.swing.JTextField txtIPadd;
    private javax.swing.JTextField txtMRN;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtName1;
    private javax.swing.JTextField txtName2;
    private javax.swing.JLabel txtPhoto;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtdeviceid;
    private javax.swing.JTextField txtdob;
    private javax.swing.JTextField txtdob1;
    private javax.swing.JTextField txtdob2;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtemail1;
    private javax.swing.JTextField txtemail11;
    private javax.swing.JTextField txtemail2;
    private javax.swing.JTextField txtemail3;
    private javax.swing.JTextField txtemail4;
    private javax.swing.JTextField txtfaxnum;
    private javax.swing.JTextField txtfaxnum1;
    private javax.swing.JTextField txtfaxnum2;
    private javax.swing.JTextField txtgeographicdata;
    private javax.swing.JTextField txtgeographicdata1;
    private javax.swing.JTextField txtgeographicdata2;
    private javax.swing.JTextField txtlicense;
    private javax.swing.JTextField txtlinkedin;
    private javax.swing.JTextField txttelnum;
    private javax.swing.JTextField txttelnum1;
    private javax.swing.JTextField txttelnum2;
    private javax.swing.JTextField txtuniquecode;
    private javax.swing.JTextField txtvehicleid;
    // End of variables declaration//GEN-END:variables

    private void displaypersonalinfo() {

        txtName.setText(person.getName());
        txtgeographicdata.setText(person.getGeographicdata());
        txtdob.setText(person.getDateofbirth());
        txttelnum.setText(person.getTelnum()==0?"":String.valueOf(person.getTelnum()));
        txtfaxnum.setText(person.getFaxnum()==0?"":String.valueOf(person.getFaxnum()));
        txtemail.setText(person.getEmail());
        txtSSN.setText(person.getSSN()==0?"":String.valueOf(person.getSSN()));
        txtMRN.setText(person.getMedicalrecordnum()==0?"":String.valueOf(person.getMedicalrecordnum()));
        txtHBP.setText(person.getHPBnum()==0?"":String.valueOf(person.getHPBnum()));
        txtBankaccnum.setText(person.getBankaccountnum()==0?"":String.valueOf(person.getBankaccountnum()));
        txtvehicleid.setText(person.getVehicleidentifier());
        txtdeviceid.setText(person.getDeviceidentifier());
        txtlicense.setText(person.getLicensenum());
        txtlinkedin.setText(person.getLinkedin());
        txtIPadd.setText(person.getIPaddress());
        txtuniquecode.setText(person.getUniqidcode());
        txtPhoto.setIcon(ResizeImage(person.getPhoto()));
           
        
    }
    
    public ImageIcon ResizeImage(String ImagePath)
    {
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(150, 150, Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }
    
}
